global using System.Text.RegularExpressions;
global using Application.Common;
global using Application.Common.Constants;
global using Application.Common.Interfaces;
global using Application.Entities;
global using Application.Parsers.CourseParsers;
global using Application.Parsers.SectionParsers;
global using Application.Parsers.TableParsers;
global using HtmlAgilityPack;
